# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yIpetBsnvobji9y-Yog81vbtCgb3WGso
"""

# https://github.com/Aru2612/Credit-default-classifier-UCI-MLR/blob/master/Credit%20Card%20Default.ipynb

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
# %matplotlib inline
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import SGDClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_validate
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
import csv

from google.colab import files


uploaded = files.upload()
##choose file named defaultofcreditcardclients.csv this is what I converted the
##excel file to when I saved into a csv file

train_data=pd.read_csv('defaultofcreditcardclients.csv')

train_data.head()

train_data.dtypes

train_data.rename(columns=(train_data.iloc[0]),inplace=True)
train_data.drop(index=[0],inplace=True)
train_data.rename(columns={'default payment next month':'Y'},inplace=True)

train_data=train_data.astype(int)

train_data.nunique()

train_data.set_index('ID',inplace=True)

plt.figure(figsize = (14,6))
plt.xlim((10000,1000000))
plt.xticks(np.arange(10000,1000000,100000))
plt.hist(train_data['LIMIT_BAL'],range=[10000,1000000],bins=30,edgecolor='#242124')
plt.title('Distribution of Credit Limit',fontsize=16,fontweight='bold')
plt.xlabel('Credit Limit',fontsize=14,fontweight='bold')
plt.ylabel('Frequency',fontsize=14,fontweight='bold')
plt.show()